package com.myharness.codex.entity.enums;

public enum AgentEventType {
    WORKSPACE_FILE_RESULT,
    REGISTER, HEARTBEAT, WORKSPACES_CHANGED, THREAD_STARTED, EXPERT_RUNTIME_UPDATED, TURN_STARTED, TURN_EVENT,
    APPROVAL_REQUIRED, APPROVAL_RESOLVED, TURN_COMPLETED, TURN_FAILED, TURN_INTERRUPTED, WORKSPACE_CREATE_RESULT, ERROR, PONG
}
