package com.myharness.codex.entity.enums;

public enum AgentCommandType {
    SYNC_WORKSPACE_TREE,
    CREATE_WORKSPACE_DIRECTORY,
    UPLOAD_WORKSPACE_FILE,
    PREPARE_WORKSPACE_DOWNLOAD,
    RELOCATE_WORKSPACE_ENTRY,
    PREPARE_WORKSPACE_DELETE,
    DELETE_WORKSPACE_ENTRY,
    PREPARE_WORKSPACE_ARCHIVE,
    RECONCILE_WORKSPACE_OPERATION,
    START_THREAD, START_TURN, INTERRUPT_TURN, RESOLVE_APPROVAL,
    INSTALL_SKILL, REMOVE_SKILL, CREATE_WORKSPACE, REFRESH_WORKSPACES, PING
}
