package com.myharness.codex.entity.enums;

public enum AgentCommandType {
    START_THREAD, START_TURN, INTERRUPT_TURN, RESOLVE_APPROVAL,
    INSTALL_SKILL, REMOVE_SKILL, CREATE_WORKSPACE, REFRESH_WORKSPACES, PING
}
